# Generated by Django 3.0.6 on 2020-05-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Your Company Name', max_length=100, verbose_name='Company Name')),
                ('focus', models.CharField(help_text='Enter Your Company Focus', max_length=200, verbose_name='Company Focus')),
                ('market', models.CharField(help_text='Enter Your Company Market Field', max_length=200, verbose_name='Things You Market')),
                ('requirement', models.CharField(help_text='Write Down Your Company Requirements', max_length=300, verbose_name='Company Requirement')),
                ('domain', models.CharField(help_text='Enter Your Domain', max_length=200, verbose_name='Comapny Domain')),
                ('sales', models.CharField(help_text='Your Sales Stratergy', max_length=400, verbose_name='Sales Stratergy')),
                ('expectation', models.CharField(help_text='What Do You Expect From Us?', max_length=400, verbose_name='Company Expectation')),
                ('audience', models.CharField(help_text='Type of audience they want to build', max_length=400, verbose_name='Audeince You Want')),
                ('audi_you', models.CharField(help_text='Type Of Audeince You Currently Own', max_length=400, verbose_name='Audience You Have')),
                ('market_status', models.CharField(help_text='Previous Market Status', max_length=400, verbose_name='Market Status')),
                ('hashtag', models.CharField(help_text='Specific Hashtag', max_length=100, verbose_name='Hashtags Used')),
                ('advt', models.CharField(help_text='Preveious Advertisement Stratergy', max_length=400, verbose_name='Advertisement Startergy')),
                ('company_profile', models.URLField(help_text='Company Profile Link', verbose_name='Company Profile')),
                ('creation', models.CharField(help_text='Content creation( Should we build our own / Creative design )', max_length=400, verbose_name=' Content Creation')),
                ('expected', models.IntegerField(help_text='Expected Price', verbose_name='Price')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
