# Generated by Django 3.0.6 on 2020-05-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='expected',
            field=models.CharField(help_text='Expected Price', max_length=7, verbose_name='Price'),
        ),
    ]
